<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kino" nsURI="http://www.beispiel.de/kino" nsPrefix="kino">
  <eClassifiers xsi:type="ecore:EClass" name="Kino">
    <eOperations name="saalAnlegen" eType="#//Kinosaal">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="filmAnlegen" eType="#//Film">
      <eParameters name="titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="dauer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="einnahmenBerechnen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="intervallStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="intervallEnde" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saele" lowerBound="1" upperBound="-1"
        eType="#//Kinosaal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kinosaal">
    <eOperations name="reiheHinzufügen">
      <eParameters name="reihe" eType="#//Sitzreihe"/>
    </eOperations>
    <eOperations name="freigeben"/>
    <eOperations name="istFreigegeben" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freigegeben" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reihen" lowerBound="1"
        upperBound="-1" eType="#//Sitzreihe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auffuehrungen" upperBound="-1"
        eType="#//Auffuehrung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Film">
    <eOperations name="gesamtEinnahmen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dauer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auffuehrungen" upperBound="-1"
        eType="#//Auffuehrung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Auffuehrung">
    <eOperations name="verfuegbarePlaetze" upperBound="-1" eType="#//Sitzplatz">
      <eParameters name="kategorie" eType="#//SitzreihenKategorie"/>
    </eOperations>
    <eOperations name="gesamtEinnahmen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startzeitpunkt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saal" lowerBound="1" eType="#//Kinosaal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservierungen" upperBound="-1"
        eType="#//Reservierung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buchungen" upperBound="-1"
        eType="#//Buchung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="film" lowerBound="1" eType="#//Film"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sitzreihe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reihennummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kategorie" eType="#//SitzreihenKategorie"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anzahlSitze" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plaetze" lowerBound="1"
        upperBound="-1" eType="#//Sitzplatz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saal" lowerBound="1" eType="#//Kinosaal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SitzreihenKategorie">
    <eLiterals name="PARKETT"/>
    <eLiterals name="LOGE" value="1"/>
    <eLiterals name="LOGE_MIT_SERVICE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sitzplatz">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platznummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reihe" lowerBound="1" eType="#//Sitzreihe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservierung" eType="#//Reservierung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buchung" eType="#//Buchung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kunde">
    <eOperations name="reservieren" eType="#//Reservierung">
      <eParameters name="auffuehrung" eType="#//Auffuehrung"/>
      <eParameters name="plaetze" lowerBound="1" upperBound="-1" eType="#//Sitzplatz"/>
    </eOperations>
    <eOperations name="reservierungStornieren">
      <eParameters name="reservierung" eType="#//Reservierung"/>
    </eOperations>
    <eOperations name="direktBuchung" eType="#//Buchung">
      <eParameters name="auffuehrung" eType="#//Auffuehrung"/>
      <eParameters name="plaetze" lowerBound="1" upperBound="-1" eType="#//Sitzplatz"/>
    </eOperations>
    <eOperations name="reservierungZuBuchungVerarbeiten" eType="#//Buchung">
      <eParameters name="reservierung" eType="#//Reservierung"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservierungen" upperBound="-1"
        eType="#//Reservierung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buchungen" upperBound="-1"
        eType="#//Buchung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reservierung">
    <eOperations name="stornieren"/>
    <eOperations name="inBuchungUmwandeln" eType="#//Buchung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reservierungsnummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startZeitstempel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kunde" lowerBound="1" eType="#//Kunde"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auffuehrung" lowerBound="1"
        eType="#//Auffuehrung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plaetze" lowerBound="1"
        upperBound="-1" eType="#//Sitzplatz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buchung">
    <eOperations name="gesamtpreis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buchungsnummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buchungsZeitstempel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bezahlt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kunde" lowerBound="1" eType="#//Kunde"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auffuehrung" lowerBound="1"
        eType="#//Auffuehrung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plaetze" lowerBound="1"
        upperBound="-1" eType="#//Sitzplatz"/>
  </eClassifiers>
</ecore:EPackage>
